/** Column layout aligned with legacy BRICS spreadsheets (e.g. Jestha 2083 export). */
export const TRANSACTION_TEMPLATE_COLUMNS = [
    "Bill Date (BS)",
    "Bill Date (AD)",
    "Travel Date",
    "Purchase Invoice No",
    "Purchase Amount",
    "Sales Date",
    "Sales Bill No",
    "Client Name",
    "PARTY",
    "Sector",
    "Sale Amount",
    "Segregate of Sales Amount as per Bill",
    "Exempt",
    "Taxable",
    "Output VAT",
    "Recieved On",
    "Received Date",
    "Receipt No",
    "Remarks",
    "Other Remarks",
    "Purchased From",
] as const;

export const TRANSACTION_TEMPLATE_SAMPLE = {
    "Bill Date (BS)": "2083-02-01",
    "Bill Date (AD)": "2026-05-15",
    "Travel Date": "2026-05-19",
    "Purchase Invoice No": "SUM012454",
    "Purchase Amount": "Rs 13,000.00",
    "Sales Date": "2026-05-17",
    "Sales Bill No": "382",
    "Client Name": "NISHA GURUNG",
    PARTY: "SUJAN BASNET",
    Sector: "DEL-KTM",
    "Sale Amount": "Rs 13,000.00",
    "Segregate of Sales Amount as per Bill": "Rs 13,000.00",
    Exempt: "Rs 13,000.00",
    Taxable: "Rs 0.00",
    "Output VAT": "Rs 0.00",
    "Recieved On": "BANK",
    "Received Date": "",
    "Receipt No": "",
    Remarks: "",
    "Other Remarks": "",
    "Purchased From": "",
};
